name: Code Validation

on:
  workflow_dispatch:
  pull_request:

jobs:
  validate-code:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/checkout@v4

      - name: npm Install
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Run Test
        run: npm run test

      - name: Run Lint
        run: npm run lint

      - name: Run Format
        run: npm run format
